package application;

public enum Property {

	MISSIONCARDSADDED, COLORCARDCHANGE, PLAYERCHANGE, DRAWMISSIONCARDS, MISSIONCARDFINISHED, MISSIONCARDHIDDEN, BUINGCONNECTION, MISSIONCARDINDEXCHANGE

}
